# Generated by Django 2.1.7 on 2019-03-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.TextField(max_length=20, verbose_name='room_id')),
                ('user_id', models.TextField(max_length=20, verbose_name='user_id')),
                ('movies', models.TextField(max_length=100000, verbose_name='movies')),
            ],
        ),
    ]
